import random
import socket
import sys
import time
import unittest
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from video_protocol import HEADER, Reassembler, packetize, Frame
from video_receiver import CameraProvider, VideoReceiver
from PySide6.QtCore import QSize

class ProtocolTests(unittest.TestCase):
    def test_full_720p_shuffled_duplicates(self):
        pixels=b'\xf8\x00\x07\xe0\x00\x1f\xff\xff'*(1280*720//4)
        packets=list(packetize(pixels,1280,720,9))
        packets+=packets[10:20]
        random.Random(42).shuffle(packets)
        r=Reassembler(); results=[]
        for p in packets:
            f=r.feed(p,now=10)
            if f:results.append(f)
        self.assertEqual(len(results),1)
        self.assertEqual(results[0].pixels,pixels)
        self.assertEqual(results[0].format,3)

    def test_missing_chunk_timeout_then_next(self):
        r=Reassembler();p=list(packetize(bytes(4000),100,20,1))
        for x in p[:-1]:self.assertIsNone(r.feed(x,now=0))
        r.expire(now=2);self.assertFalse(r.pending)
        result=None
        for x in packetize(bytes(4000),100,20,2):result=r.feed(x,now=2)
        self.assertEqual(result.sequence,2)

    def test_old_frame_does_not_overwrite_new(self):
        r=Reassembler()
        self.assertIsNotNone(r.feed(next(packetize(b'\x00\x00',1,1,100)),now=1))
        self.assertIsNone(r.feed(next(packetize(b'\x00\x00',1,1,99)),now=1))

    def test_sequence_wrap(self):
        r=Reassembler()
        for seq in (0xffffffff,0,1):
            self.assertIsNotNone(r.feed(next(packetize(bytes(2),1,1,seq)),now=1))

    def test_restart_and_old_session(self):
        r=Reassembler()
        p=lambda session:next(packetize(bytes(2),1,1,1,session))
        self.assertIsNotNone(r.feed(p(1),now=1))
        self.assertIsNone(r.feed(p(2),now=1.1))
        self.assertIsNotNone(r.feed(p(2),now=3))
        self.assertIsNone(r.feed(p(1),now=3.1))

    def test_malformed_and_resource_limit(self):
        r=Reassembler()
        good=next(packetize(bytes(2),1,1,1))
        for bad in (b'',good[:-1],good+b'\0',b'BAD!'+good[4:]):
            self.assertIsNone(r.feed(bad))
        for field,value in ((2,9),(3,65535),(5,100),(6,0),(9,0xffffffff)):
            h=list(HEADER.unpack_from(good));h[field]=value
            self.assertIsNone(r.feed(HEADER.pack(*h)+good[HEADER.size:]))
        for i in range(20):r.feed(next(packetize(bytes(4000),100,20,i)),now=1)
        self.assertLessEqual(len(r.pending),3)

    def test_rgb565_colours_and_odd_stride(self):
        provider=CameraProvider()
        provider.set_frame(Frame(3,1,b'\xf8\x00\x07\xe0\x00\x1f',1,3))
        size=QSize();image=provider.requestImage('',size,QSize())
        self.assertEqual(size,QSize(3,1))
        for x,expected in enumerate(((255,0,0),(0,255,0),(0,0,255))):
            c=image.pixelColor(x,0)
            self.assertEqual((c.red(),c.green(),c.blue()),expected)

    def test_c_header_fixture(self):
        fixture=Path(__file__).with_name('c_wire_fixture.bin')
        if not fixture.exists():self.skipTest('C fixture generated by validation harness')
        frame=Reassembler().feed(fixture.read_bytes())
        self.assertEqual((frame.width,frame.height,frame.format),(3,1,3))
        self.assertEqual(frame.pixels,b'\xf8\x00\x07\xe0\x00\x1f')

    def test_loopback_720p_and_clean_stop(self):
        receiver=VideoReceiver('127.0.0.1',0,'127.0.0.1')
        sender=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
        port=receiver.sock.getsockname()[1]
        try:
            pixels=b'\x07\xe0'*(1280*720)
            for p in packetize(pixels,1280,720,4):
                sender.sendto(p,('127.0.0.1',port))
                time.sleep(0.0001)
            end=time.monotonic()+2;result=None
            while result is None and time.monotonic()<end:
                result=receiver.take_latest();time.sleep(.01)
            self.assertIsNotNone(result)
            self.assertEqual(result[0].pixels,pixels)
            self.assertIsNone(receiver.error)
        finally:
            sender.close();receiver.close()
        self.assertFalse(receiver.thread.is_alive())

if __name__=='__main__':unittest.main(verbosity=2)
